python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13

c_stdlib_version: # [unix]
  - 2.17          # [linux]
  - 2.34          # [linux]

cuda_compiler_version_min: # [unix]
  - 12.6                   # [linux]
