c_stdlib_version:              # [unix]
  - 2.34                       # [linux]
  - 2.34                       # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
cuda_compiler_version_min:
  - 12.6
